services:
  st_app:
    container_name: st_app
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      PORT: "3000"
    volumes:
      - "./storage:/app/storage"
    networks:
      - "global_network"

networks:
  global_network:
    external: true
